import tempfile
import unittest
from pathlib import Path

from taskbot.storage import Storage


class StorageTests(unittest.TestCase):
    def test_draft_lifecycle_and_update_deduplication(self):
        with tempfile.TemporaryDirectory() as tmp:
            store = Storage(Path(tmp) / "taskbot.sqlite3")
            self.assertFalse(store.seen_update(7))
            store.mark_update(7)
            self.assertTrue(store.seen_update(7))
            draft = store.create_draft("Согласовать смету", 2, 1, "2026-08-18T19:00:00+03:00", "high")
            self.assertEqual(store.get_pending(draft.id).title, "Согласовать смету")
            self.assertEqual(store.latest_pending_draft(1).id, draft.id)
            self.assertEqual(store.get_pending(draft.id).priority, "high")
            updated = store.update_draft(draft.id, title="Уточнить смету", priority="low", responsible_id=3)
            self.assertEqual(updated.title, "Уточнить смету")
            self.assertEqual(updated.priority, "low")
            self.assertEqual(updated.responsible_id, 3)
            store.set_status(draft.id, "created")
            self.assertIsNone(store.get_pending(draft.id))
            self.assertTrue(store.claim_routine("morning", "2026-08-18", 1))
            self.assertFalse(store.claim_routine("morning", "2026-08-18", 1))
            store.set_mode(1, "assign", "partner")
            self.assertEqual(store.pop_mode(1), ("assign", "partner"))
            self.assertIsNone(store.pop_mode(1))
            tasks = [{"id": "42", "title": "Согласовать смету", "deadline": "2026-08-19T10:00:00+03:00", "priority": "1"}]
            snapshots = store.sync_task_snapshots(1, tasks)
            self.assertEqual(snapshots[0].task_id, "42")
            self.assertEqual(store.get_snapshot(1, "42").priority, "1")
            self.assertFalse(store.reminder_was_sent(1, "42", "day", "bucket"))
            store.mark_reminder_sent(1, "42", "day", "bucket")
            self.assertTrue(store.reminder_was_sent(1, "42", "day", "bucket"))
            store.set_snooze(1, "42", "2026-08-18T12:00:00+03:00")
            self.assertIsNotNone(store.get_snooze(1, "42"))
            store.clear_snooze(1, "42")
            self.assertIsNone(store.get_snooze(1, "42"))
            store.register_managed_task("42", 1, 2, "Согласовать смету")
            managed = store.managed_task("42")
            self.assertEqual(managed.responsible_tg_id, 2)
            self.assertEqual(len(store.incoming_tasks(2)), 1)
            self.assertEqual(len(store.delegated_tasks(1)), 1)
            self.assertIsNone(managed.accepted_at)
            store.mark_accepted("42")
            store.mark_completed("42")
            store.record_event("42", 2, "result", "Смета согласована")
            managed = store.managed_task("42")
            self.assertIsNotNone(managed.accepted_at)
            self.assertIsNotNone(managed.completed_at)
            summary = store.weekly_summary(2, "2000-01-01T00:00:00+00:00")
            self.assertEqual(summary["created"], 1)
            self.assertEqual(summary["result"], 1)
            self.assertEqual(summary["open"], 0)
            self.assertEqual(store.incoming_tasks(2), [])
            self.assertEqual(store.delegated_tasks(1), [])
            action = store.create_pending_action(1, "reschedule", "42", "2026-08-20T10:00:00+03:00")
            self.assertEqual(store.get_pending_action(action.id).kind, "reschedule")
            store.set_action_status(action.id, "confirmed")
            self.assertIsNone(store.get_pending_action(action.id))
            store.remember(1, "user", "Первая реплика")
            store.remember(1, "user", "Вторая реплика")
            self.assertEqual(store.recent_memory(1)[-1], ("user", "Вторая реплика"))
            self.assertIsNone(store.conversation_state(1).last_task_id)
            store.set_conversation_state(1, last_task_id="42", last_draft_id=draft.id)
            state = store.conversation_state(1)
            self.assertEqual(state.last_task_id, "42")
            self.assertEqual(state.last_draft_id, draft.id)
            store.record_correction(1, draft.id, "Старый текст", "Раздели на две")
            self.assertEqual(store.recent_corrections(1)[-1], ("Старый текст", "Раздели на две"))
            store.remember_fact(1, "Дима — мой партнёр")
            store.remember_fact(1, "Задачи без срока ставь на завтра в 10:00")
            self.assertEqual(len(store.memories(1)), 2)
            self.assertEqual(store.forget_memories(1, "Дима"), 1)
            self.assertEqual(store.memories(1), ["Задачи без срока ставь на завтра в 10:00"])
            inbox = store.capture_inbox(1, "Подумать про новую базу клиентов")
            self.assertEqual(store.inbox_items(1)[0].id, inbox.id)
            store.set_inbox_status(inbox.id, "drafted")
            self.assertEqual(store.inbox_items(1), [])
            self.assertTrue(store.add_focus(1, "2026-08-18", "42"))
            self.assertTrue(store.add_focus(1, "2026-08-18", "43"))
            self.assertTrue(store.add_focus(1, "2026-08-18", "44"))
            self.assertFalse(store.add_focus(1, "2026-08-18", "45"))
            self.assertEqual(store.focus_task_ids(1, "2026-08-18"), ["42", "43", "44"])
            store.remove_focus(1, "2026-08-18", "44")
            project = store.create_project(1, "Тендеры")
            self.assertEqual(store.projects(1)[0].title, "Тендеры")
            goal = store.create_goal(1, project.id, "Подать пять тендеров")
            self.assertEqual(store.goals(1, project.id)[0].id, goal.id)
            store.set_task_project(1, "42", project.id)
            self.assertEqual(store.task_project(1, "42").title, "Тендеры")
            runtime = store.update_task_runtime("42", responsible_tg_id=2, state="in_progress", next_step="Позвонить клиенту", started=True)
            self.assertEqual(runtime.state, "in_progress")
            self.assertEqual(runtime.next_step, "Позвонить клиенту")
            runtime = store.update_task_runtime("42", state="blocked", blocker="Ждём КП", last_progress="Смета отправлена")
            self.assertEqual(runtime.blocker, "Ждём КП")
            self.assertEqual(store.task_runtime("42").last_progress, "Смета отправлена")
            store.record_event("42", 2, "blocked", "Ждём КП")
            self.assertEqual(store.task_events("42")[-1][0], "blocked")
            store.remember_task_card(2, "42", 2, 901)
            card = store.task_card(2, "42")
            self.assertEqual((card.chat_id, card.message_id), (2, 901))
            self.assertEqual(store.task_for_message(2, 2, 901), "42")
            store.bind_task_message(2, "42", 2, 902)
            self.assertEqual(store.task_for_message(2, 2, 902), "42")
            backup = Path(tmp) / "backup.sqlite3"
            store.backup(backup)
            self.assertTrue(backup.exists())
            store.close()


if __name__ == "__main__":
    unittest.main()
